name: Viet travel - CICD
run-name: Deploy branch ${{ github.ref_name }} to production

on:
  push:
    branches:
      - release/*

permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  cleanup:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Clean up temporary files
        run: |
          echo "Started cleaning up temporary files..."
          rm -rf /home/ubuntu/actions-runner/viet-travel/viet-travel-fe/viet-travel-fe/dist/viet-travel-fe/*

  build-to-target:
    runs-on: self-hosted
    needs: cleanup
    env:
      NODE_ENV: production_build
      BUILD_FOLDER: /home/ubuntu/actions-runner/viet-travel/viet-travel-fe/viet-travel-fe/dist/viet-travel-fe
      DEPLOY_PATH: /var/www/viet-travel-fe/
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          
      - name: Install dependencies needed
        run: |
          npm install

      - name: Build the project
        run: |
          export NODE_OPTIONS=--max-old-space-size=4096
          npm run build

      - name: Verify build folder
        run: |
          echo "Listing files in build directory:"
          ls -la $BUILD_FOLDER

      - name: Create build folder
        run: |
          mkdir -p $DEPLOY_PATH
          cp -r $BUILD_FOLDER* $DEPLOY_PATH

      - name: Verify copied files
        run: |
          echo "Listing files in /home/ubuntu/fe:"
          ls -la $DEPLOY_PATH

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: $DEPLOY_PATH
          if-no-files-found: warn
          compression-level: 6
          overwrite: false
          include-hidden-files: false
        env:
          NODE_ENV: production_build

  deploy-temp:
    runs-on: self-hosted
    needs: build-to-target
    env:
      DEPLOY_PATH: "/var/www/viet-travel-fe"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SSH client
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass

      - name: Deploy to server
        run: |
          echo "Deploying to $DEPLOY_PATH"
          # sshpass -p "$REMOTE_PW" scp -r -o StrictHostKeyChecking=no viet-travel-fe/stub/* root@"$REMOTE_HOST":"$DEPLOY_PATH"
        env:
          REMOTE_PW: ${{ secrets.REMOTE_PW }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
