name: CI/CD Pipeline

on:
  push:
    branches:
      - release/*

jobs:
  cleanup:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Clean up temporary files
        run: |
          echo "Started cleaning up temporary files..."
          rm -rf viet-travel-fe/*

  build:
    runs-on: self-hosted
    needs: cleanup
    env:
      NODE_ENV: production_build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          
      - name: Install dependencies needed
        run: |
          npm install

      - name: Build the project
        run: |
          export NODE_OPTIONS=--max-old-space-size=4096
          CI=false npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: viet-travel-fe/stub/

  deploy:
    runs-on: self-hosted
    needs: build
    env:
      DEPLOY_PATH: "/var/www/viet-travel-fe"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SSH client
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass

      - name: Deploy to server
        run: |
          echo "Deploying to $DEPLOY_PATH"
          sshpass -p "$REMOTE_PW" scp -r -o StrictHostKeyChecking=no viet-travel-fe/stub/* root@"$REMOTE_HOST":"$DEPLOY_PATH"
        env:
          REMOTE_PW: ${{ secrets.REMOTE_PW }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
