name: GitHub Pages Sample

on:
  push:
    branches:
    - release/*

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    # - name: Run tests
    #   run: npm run test

    - name: Build
      run: npm run build:prod

    - name: Deploy
      if: success()
      uses: peaceiris/actions-fast-build@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: dist/viet-travel-be
        enable_jekyll: true
